[package]
name = "flairy-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "Flairy"
path = "src/main.rs"

[dependencies]
gpui = { version = "0.2", features = ["runtime_shaders"] }
gpui-component = "0.5"
anyhow = "1"
rust-embed = "8"
flairy-agent = { path = "crates/flairy-agent" }
flairy-markdown = { path = "crates/flairy-markdown" }
flairy-contract = { path = "../../crates/flairy-contract" }
flairy-ai = { path = "crates/flairy-ai" }
tokio = { version = "1", features = ["sync", "rt-multi-thread", "process"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
rusqlite = { version = "0.32", features = ["bundled"] }
rust_socketio = "0.6"
reqwest = { version = "0.12", features = ["json", "blocking"] }
rmcp = { version = "3.0.1", features = ["client", "transport-child-process", "transport-streamable-http-client-reqwest"] }
keyring = "4.1.5"

[profile.dev]
debug = 1

[profile.release]
lto = "thin"
strip = true
