import { realpath, stat } from 'node:fs/promises'
import { basename } from 'node:path'
import { Type } from 'typebox'
import type { AgentTool } from '@earendil-works/pi-agent-core'
import { resolveToCwd } from './paths'

/** Register an existing output (including files created by shell tools) for UI. */
export function createPresentFileTool(cwd: string): AgentTool<any> {
  return {
    name: 'present_file',
    label: 'present_file',
    description:
      'Make an existing output file available for the user to preview or save. Accepts a file inside the working directory, including PDFs, spreadsheets and images generated by other tools. Returns an Artifact ID for a ui:artifact card. Does not modify or upload the file.',
    parameters: Type.Object({
      path: Type.String({ description: 'Output file path relative to the working directory' })
    }),
    execute: async (id, { path }: any, signal) => {
      signal?.throwIfAborted()
      const root = await realpath(cwd)
      const file = await realpath(resolveToCwd(path, cwd))
      resolveToCwd(file, root)
      const info = await stat(file)
      if (!info.isFile()) throw new Error('Not a file')
      signal?.throwIfAborted()
      return {
        content: [
          {
            type: 'text',
            text: `File ready: ${basename(file)} (${info.size} bytes). Artifact ID: ${id}. Present it with a ui:artifact card using this exact artifactId.`
          }
        ],
        details: { artifact: { id, path: file } }
      }
    }
  }
}
